#
# Module manifest for module 'PKI-Consolidation'
#
# Generated by: Adrian Johnson
# Generated on: 10/18/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PKI-Consolidation.psm1'

# Version number of this module.
ModuleVersion = '1.3.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'a7b3c4d5-e6f7-8901-2345-67890abcdef1'

# Author of this module
Author = 'Adrian Johnson'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) 2025 Adrian Johnson. All rights reserved. Licensed under MIT.'

# Description of the functionality provided by this module
Description = @'
Enterprise PKI Consolidation Tool for Active Directory Certificate Services (AD CS).

Complete end-to-end workflow for consolidating PKI hierarchies during mergers, acquisitions, 
or infrastructure modernization. Features enterprise-grade security hardening, performance 
optimization, OCSP health monitoring, and comprehensive reporting.

Key Features:
- Complete 9-phase PKI consolidation workflow
- Security hardening (HMAC logging, privilege validation, input sanitization)
- Performance optimization (caching, parallel processing for PowerShell 7+)
- OCSP responder health monitoring
- Beautiful HTML verification reports
- Azure Key Vault and Keyfactor integration
- Automated helper script generation
- Comprehensive test suite (75+ Pester tests)

Perfect for: PKI administrators, enterprise architects, and security teams managing 
Active Directory Certificate Services environments.
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'modules\PKI-Security.psm1',
    'modules\PKI-Performance.psm1',
    'modules\PKI-OCSP.psm1',
    'modules\PKI-Dashboard.psm1',
    'modules\PKI-Compliance.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Main workflow functions
    'Start-PKIConsolidation',
    'Invoke-Phase1Audit',
    'Invoke-Phase2SelectRoot',
    'Invoke-Phase3NewSubCSR',
    'Invoke-Phase4AcceptAndPublish',
    'Invoke-Phase4APublishChanges',
    'Invoke-Phase4BGuardedChanges',
    'Invoke-Phase5TrustPropagation',
    'Invoke-Phase6CloudIntegrations',
    'Invoke-Phase7LeafReissue',
    'Invoke-Phase8Verify',
    'Invoke-Phase9DecommissionLegacy',
    
    # Security module functions
    'Get-PKICredential',
    'Set-PKICredential',
    'Remove-PKICredential',
    'Test-RequiredPrivileges',
    'Set-SecureDirectoryPermissions',
    'Write-SecureLog',
    'Test-LogIntegrity',
    'Test-SafePath',
    'Test-SafeFileName',
    'Test-SafeCAName',
    
    # Performance module functions
    'Get-CachedCertStore',
    'Find-CachedCertificate',
    'Clear-CertStoreCache',
    'Test-ParallelSupport',
    'Invoke-ParallelCAProcessing',
    'Start-PerformanceTimer',
    'Stop-PerformanceTimer',
    'Measure-OperationPerformance',
    
    # OCSP module functions
    'Test-OCSPResponder',
    'Get-OCSPResponderFromCertificate',
    'Test-CertificateOCSP',
    'Test-CAOCSPHealth',
    'Measure-OCSPPerformance',
    
    # Dashboard module functions
    'Get-PKIDashboardData',
    'New-PKIDashboard',
    'Start-PKIDashboard',
    
    # Compliance module functions
    'Test-NIST80053Compliance',
    'Test-CISBenchmarkCompliance',
    'New-PKIComplianceReport',
    'New-PKIComplianceSchedule'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'PKI-Consolidation.psm1',
    'PKI-Consolidation.psd1',
    'PKI-Consolidation-Enhanced.ps1',
    'modules\PKI-Security.psm1',
    'modules\PKI-Performance.psm1',
    'modules\PKI-OCSP.psm1',
    'scripts\Setup-PKICredentials.ps1',
    'scripts\Test-PKIReadiness.ps1',
    'scripts\Test-CAHealth.ps1',
    'README.md',
    'LICENSE',
    'CHANGELOG.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'PKI',
            'CertificateServices',
            'ADCS',
            'ActiveDirectory',
            'Certificates',
            'Security',
            'Enterprise',
            'Consolidation',
            'Merger',
            'CA',
            'CertificateAuthority',
            'OCSP',
            'CRL',
            'Windows',
            'WindowsServer'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/adrian207/PKI-Consolidation/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/adrian207/PKI-Consolidation'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/adrian207/PKI-Consolidation/main/assets/icon.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
# v1.3.0 Release Notes

## Complete PKI Consolidation Workflow

This release delivers a production-ready, end-to-end PKI consolidation solution with all 9 phases:

### All Phases Implemented
1. **CA Discovery** - Automatic Active Directory scanning
2. **Root Selection** - Intelligent authoritative root identification
3. **CSR Generation** - Sub-CA certificate request creation
4. **Certificate Publishing** - AD integration and trust establishment
5. **CRL/AIA Distribution** - Automated distribution point configuration
6. **Trust Propagation** - GPO-based deployment automation
7. **Cloud Integration** - Azure Key Vault and Keyfactor support
8. **Re-enrollment** - Client certificate renewal automation
9. **Verification** - Professional HTML reporting
10. **Decommissioning** - Safe legacy CA retirement

### Key Features
- Enterprise-grade security hardening (HMAC logging, privilege validation)
- Performance optimization (certificate caching, parallel processing)
- OCSP health monitoring
- Comprehensive test suite (75+ Pester tests)
- Beautiful HTML reports
- Automated helper script generation

### Requirements
- PowerShell 5.1+ (7.0+ recommended for parallel features)
- Windows Server 2012 R2 or later
- Active Directory Certificate Services (AD CS)
- Enterprise Admin privileges

See CHANGELOG.md for complete details.
'@

        # Prerelease string of this module
        # Prerelease = 'alpha'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/adrian207/PKI-Consolidation/wiki'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

